[[idpack]]
IdPack
------

image:https://img.shields.io/gem/v/id_pack.svg[
	Gem Version, link="https://rubygems.org/gems/id_pack"]
image:https://img.shields.io/travis/riboseinc/id_pack/master.svg[
	Build Status, link="https://travis-ci.org/riboseinc/id_pack"]
image:https://api.codeclimate.com/v1/badges/655d7aa547daa7b45148/maintainability[
	"Code Climate", link="https://codeclimate.com/github/riboseinc/id_pack/maintainability"]
image:https://img.shields.io/codecov/c/github/riboseinc/id_pack.svg[
	"Test Coverage", link="https://codecov.io/gh/riboseinc/id_pack"]

TODO: Add introduction

[[installation]]
Installation
~~~~~~~~~~~~

Add this line to your application’s Gemfile:

[source,ruby]
----
gem 'id_pack'
----

And then execute:

....
$ bundle
....

Or install it yourself as:

....
$ gem install id_pack
....

[[usage]]
Usage
~~~~~

TODO: Write usage instructions here

[[development]]
Development
~~~~~~~~~~~

After checking out the repo, run `bin/setup` to install dependencies.
Then, run `rake spec` to run the tests. You can also run `bin/console`
for an interactive prompt that will allow you to experiment.

To install this gem onto your local machine, run
`bundle exec rake install`. To release a new version, update the version
number in `version.rb`, and then run `bundle exec rake release`, which
will create a git tag for the version, push git commits and tags, and
push the `.gem` file to https://rubygems.org[rubygems.org].

[[contributing]]
Contributing
~~~~~~~~~~~~

Bug reports and pull requests are welcome on GitHub at
https://github.com/riboseinc/id_pack. This project is intended to be a
safe, welcoming space for collaboration, and contributors are expected
to adhere to the http://contributor-covenant.org[Contributor Covenant]
code of conduct.
